# Number of days of inactivity before an issue becomes stale
daysUntilStale: 180
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 15
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  **This issue had no activity for at least half a year.**  
  It's subject to automatic issue closing if there is no activity in the next 15 days.  
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false