'use strict';

/* global describe, it */

const path = require('path');
const webpack = require('webpack');
const Server = require('webpack-dev-server/lib/Server');
const request = require('supertest');
var HtmlWebpackPlugin = require('../index.js');

var OUTPUT_DIR = path.join(__dirname, '../dist');
let server, config;

function testDevConfig (config) {
  const compiler = webpack(config);
  const options = {compress: true, quiet: true};

  server = new Server(compiler, options);
  server.listen(8080, 'localhost', function (err) {
    if (err) return err;

    request.get(/static/).expect(200);

    server.close();
  });
}

describe('webpack-dev-server should not apply publicPath to index.html generated by html-webpack-plugin', function () {
  it('checks that publicPath does not affect path, from which index.html is served', function () {
    config = {
      entry: path.join(__dirname, 'fixtures/index.js'),
      output: {
        path: OUTPUT_DIR,
        filename: 'index_bundle.js'
      },
      plugins: [new HtmlWebpackPlugin()],
      devServer: {
        publicPath: '/static/'
      }
    };
    testDevConfig(config);
  });
});
