'use strict';

const webpack = require('webpack');
const Server = require('webpack-dev-server/lib/Server');

let server, config;

describe("webpack-dev-server should not apply publicPath to index.html generated by html-webpack-plugin", function () {
  it ('checks that publicPath does not affect path, from which index.html is served') {
    config = {
      entry: path.join(__dirname, 'fixtures/index.js'),
      output: {
        path: OUTPUT_DIR,
        filename: 'index_bundle.js'
      },
      plugins: [new HtmlWebpackPlugin()],
      devServer: {
        publicPath: '/static/'
      }
    };

    const compiler = webpack(config);
    const options = {compress: true, quiet: true};
    server = new Server(compiler, options);

    server.listen(8080, 'localhost', (err) => {
      if (err) return done(err);
      done();
    });


    if (server) {
      server.close(() => {
        server = null;
        done();
      });
    } else {
      done();
    }

  }
});
